<?php

// Creation du fichier
if (!$file = fopen("resultats/".$namefile.".xml","w+")) 
{
	echo "Echec de l'ouverture du fichier";
}
else 
{
	$str = 
"<MonkeyCantab>
<Version>MonkeyCantab configuration v8.6</Version>
<GeneralParameters>
<BackgroundBlue>0</BackgroundBlue>
<BackgroundGreen>0</BackgroundGreen>
<BackgroundRed>0</BackgroundRed>
<Comment>(add your comment here)</Comment>
<Database></Database>
<DisableHouselightDuringTasks>0</DisableHouselightDuringTasks>
<LinkDuration>1</LinkDuration>
<LinkUseHouselight>0</LinkUseHouselight>
<MaxTimeToWaitForFingerRemovalSec>0</MaxTimeToWaitForFingerRemovalSec>
<MediaDirectory></MediaDirectory>
<NumModules>1</NumModules>
<NumObjects>1</NumObjects>
<OverallMaxRewards>0</OverallMaxRewards>
<RespondToMouse>0</RespondToMouse>
<Session>1</Session>
<StartWithLink>0</StartWithLink>
<StrictTouches>0</StrictTouches>
<Subject>xxx</Subject>
<SummaryFile>xxx-18May2013-1524-MonkeyCantab-summary.txt</SummaryFile>
<DefaultReward>
<m_bDarkness>0</m_bDarkness>
<m_bDatabaseConsidersThisReward>1</m_bDatabaseConsidersThisReward>
<m_bExtraPunishmentDevice>0</m_bExtraPunishmentDevice>
<m_bExtraRewardDevice>0</m_bExtraRewardDevice>
<m_bGivePellet>1</m_bGivePellet>
<m_bGivePump>0</m_bGivePump>
<m_bGivePump2>0</m_bGivePump2>
<m_bGiveVisualStimulus>0</m_bGiveVisualStimulus>
<m_bPump2Contingent>1</m_bPump2Contingent>
<m_bPumpContingent>1</m_bPumpContingent>
<m_bUseMagazineLamp>0</m_bUseMagazineLamp>
<m_bUseReinforcementInfoLine>1</m_bUseReinforcementInfoLine>
<m_dwPelletPulseLengthMs>45</m_dwPelletPulseLengthMs>
<m_dwReinforcementInfoLinePulseMs>10</m_dwReinforcementInfoLinePulseMs>
<m_fDarknessTimeSec>10</m_fDarknessTimeSec>
<m_fExtraPunishmentDeviceDurationSec>5</m_fExtraPunishmentDeviceDurationSec>
<m_fExtraRewardDeviceDurationSec>5</m_fExtraRewardDeviceDurationSec>
<m_fInterPelletGapSec>0.5</m_fInterPelletGapSec>
<m_fPump2ContPumpTimeSec>1</m_fPump2ContPumpTimeSec>
<m_fPump2DurationSec>5</m_fPump2DurationSec>
<m_fPumpContPumpTimeSec>1</m_fPumpContPumpTimeSec>
<m_fPumpDurationSec>5</m_fPumpDurationSec>
<m_fVisualStimulusDurationSec>2</m_fVisualStimulusDurationSec>
<m_fVisualStimulusOffTimeSec>0.5</m_fVisualStimulusOffTimeSec>
<m_fVisualStimulusOnTimeSec>0.5</m_fVisualStimulusOnTimeSec>
<m_iPelletsPerReinf>1</m_iPelletsPerReinf>
<m_iVisualStimulusXCoord>500</m_iVisualStimulusXCoord>
<m_iVisualStimulusYCoord>375</m_iVisualStimulusYCoord>
<m_strVisualStimulusName>whiteScreen</m_strVisualStimulusName>
<m_sound>
<m_bPlaySound>1</m_bPlaySound>
<m_bSoundIsWav>0</m_bSoundIsWav>
<m_enumSoundType>1</m_enumSoundType>
<m_fSoundDurationSec>1</m_fSoundDurationSec>
<m_iSoundFrequencyHz>1000</m_iSoundFrequencyHz>
<m_iSoundLevelDb>85</m_iSoundLevelDb>
<m_strSoundFile></m_strSoundFile>
</m_sound>
</DefaultReward>
<DefaultPunishment>
<m_bDarkness>1</m_bDarkness>
<m_bDatabaseConsidersThisReward>0</m_bDatabaseConsidersThisReward>
<m_bExtraPunishmentDevice>0</m_bExtraPunishmentDevice>
<m_bExtraRewardDevice>0</m_bExtraRewardDevice>
<m_bGivePellet>0</m_bGivePellet>
<m_bGivePump>0</m_bGivePump>
<m_bGivePump2>0</m_bGivePump2>
<m_bGiveVisualStimulus>1</m_bGiveVisualStimulus>
<m_bPump2Contingent>1</m_bPump2Contingent>
<m_bPumpContingent>1</m_bPumpContingent>
<m_bUseMagazineLamp>0</m_bUseMagazineLamp>
<m_bUseReinforcementInfoLine>1</m_bUseReinforcementInfoLine>
<m_dwPelletPulseLengthMs>45</m_dwPelletPulseLengthMs>
<m_dwReinforcementInfoLinePulseMs>20</m_dwReinforcementInfoLinePulseMs>
<m_fDarknessTimeSec>5</m_fDarknessTimeSec>
<m_fExtraPunishmentDeviceDurationSec>10</m_fExtraPunishmentDeviceDurationSec>
<m_fExtraRewardDeviceDurationSec>5</m_fExtraRewardDeviceDurationSec>
<m_fInterPelletGapSec>0.5</m_fInterPelletGapSec>
<m_fPump2ContPumpTimeSec>1</m_fPump2ContPumpTimeSec>
<m_fPump2DurationSec>5</m_fPump2DurationSec>
<m_fPumpContPumpTimeSec>1</m_fPumpContPumpTimeSec>
<m_fPumpDurationSec>5</m_fPumpDurationSec>
<m_fVisualStimulusDurationSec>2</m_fVisualStimulusDurationSec>
<m_fVisualStimulusOffTimeSec>0.5</m_fVisualStimulusOffTimeSec>
<m_fVisualStimulusOnTimeSec>0.5</m_fVisualStimulusOnTimeSec>
<m_iPelletsPerReinf>1</m_iPelletsPerReinf>
<m_iVisualStimulusXCoord>500</m_iVisualStimulusXCoord>
<m_iVisualStimulusYCoord>375</m_iVisualStimulusYCoord>
<m_strVisualStimulusName>whiteScreen</m_strVisualStimulusName>
<m_sound>
<m_bPlaySound>1</m_bPlaySound>
<m_bSoundIsWav>0</m_bSoundIsWav>
<m_enumSoundType>1</m_enumSoundType>
<m_fSoundDurationSec>2</m_fSoundDurationSec>
<m_iSoundFrequencyHz>40</m_iSoundFrequencyHz>
<m_iSoundLevelDb>85</m_iSoundLevelDb>
<m_strSoundFile></m_strSoundFile>
</m_sound>
</DefaultPunishment>
<SoundLink>
<m_bPlaySound>1</m_bPlaySound>
<m_bSoundIsWav>0</m_bSoundIsWav>
<m_enumSoundType>0</m_enumSoundType>
<m_fSoundDurationSec>1</m_fSoundDurationSec>
<m_iSoundFrequencyHz>100</m_iSoundFrequencyHz>
<m_iSoundLevelDb>100</m_iSoundLevelDb>
<m_strSoundFile></m_strSoundFile>
</SoundLink>
<SoundMarker1>
<m_bPlaySound>1</m_bPlaySound>
<m_bSoundIsWav>0</m_bSoundIsWav>
<m_enumSoundType>3</m_enumSoundType>
<m_fSoundDurationSec>1</m_fSoundDurationSec>
<m_iSoundFrequencyHz>500</m_iSoundFrequencyHz>
<m_iSoundLevelDb>100</m_iSoundLevelDb>
<m_strSoundFile></m_strSoundFile>
</SoundMarker1>
<SoundMarker2>
<m_bPlaySound>1</m_bPlaySound>
<m_bSoundIsWav>0</m_bSoundIsWav>
<m_enumSoundType>3</m_enumSoundType>
<m_fSoundDurationSec>1</m_fSoundDurationSec>
<m_iSoundFrequencyHz>500</m_iSoundFrequencyHz>
<m_iSoundLevelDb>100</m_iSoundLevelDb>
<m_strSoundFile></m_strSoundFile>
</SoundMarker2>
<SoundMarker3>
<m_bPlaySound>1</m_bPlaySound>
<m_bSoundIsWav>0</m_bSoundIsWav>
<m_enumSoundType>1</m_enumSoundType>
<m_fSoundDurationSec>1</m_fSoundDurationSec>
<m_iSoundFrequencyHz>300</m_iSoundFrequencyHz>
<m_iSoundLevelDb>85</m_iSoundLevelDb>
<m_strSoundFile></m_strSoundFile>
</SoundMarker3>
</GeneralParameters>
<ObjectNames>
<Object_0>whiteScreen</Object_0>
</ObjectNames>
<ObjectConfigurations>
<Object_0>
<whiteScreen>
<NumComponents>1</NumComponents>
<ObjectName>whiteScreen</ObjectName>
<ComponentTypes>
<Component_0>Bitmap</Component_0>
</ComponentTypes>
<Component_0>
<m_bStretch>0</m_bStretch>
<m_iHeight>-1</m_iHeight>
<m_iLeft>0</m_iLeft>
<m_iTop>0</m_iTop>
<m_iWidth>-1</m_iWidth>
<m_strFilename>C:\white.bmp</m_strFilename>
<m_strName>BMP_White</m_strName>
</Component_0>
</whiteScreen>
</Object_0>
</ObjectConfigurations>
<ModuleNames>
<Task_0>DMTS</Task_0>
</ModuleNames>
<ModuleConfigurations>
<Task_0>
<DMTS>
<Level_0_Delay>".$elem[6]."</Level_0_Delay>
<NumLevelDelays>1</NumLevelDelays>
<NumStimuli>0</NumStimuli>
<m_bCorrectionIfWrongInPhase2>0</m_bCorrectionIfWrongInPhase2>
<m_bJumbleVariants>1</m_bJumbleVariants>
<m_bMagazineLightForInitiation>0</m_bMagazineLightForInitiation>
<m_bMatching>".$elem[7]."</m_bMatching>
<m_bMustTouchPhase1Stimulus>".$elem[4]."</m_bMustTouchPhase1Stimulus>
<m_bPhase1DrawWithoutReplacement>0</m_bPhase1DrawWithoutReplacement>
<m_bPhase1StimulusIsFirstOfSet>0</m_bPhase1StimulusIsFirstOfSet>
<m_bPhase2DrawWithoutReplacement>0</m_bPhase2DrawWithoutReplacement>
<m_bRepeatTrialIfFailure>0</m_bRepeatTrialIfFailure>
<m_bRewardedForTouchingPhase1Stimulus>0</m_bRewardedForTouchingPhase1Stimulus>
<m_bShuffleQuadrants>1</m_bShuffleQuadrants>
<m_bSpecifyStimuliByHand>0</m_bSpecifyStimuliByHand>
<m_bTouchResetsDelay>0</m_bTouchResetsDelay>
<m_bTouchResetsITI>0</m_bTouchResetsITI>
<m_bUseRotation>0</m_bUseRotation>
<m_fCorrectionPhaseMaxTimeToWaitForRelease>0</m_fCorrectionPhaseMaxTimeToWaitForRelease>
<m_fInitiationLimHold>10</m_fInitiationLimHold>
<m_fMaxIntertrialTimeSec>1</m_fMaxIntertrialTimeSec>
<m_fMaxResponseTimePhase1Sec>".$elem[2]."</m_fMaxResponseTimePhase1Sec>
<m_fMaxResponseTimePhase2Sec>".$elem[3]."</m_fMaxResponseTimePhase2Sec>
<m_fMaxTimeMinutes>60</m_fMaxTimeMinutes>
<m_fMinIntertrialTimeSec>1</m_fMinIntertrialTimeSec>
<m_fPhase1StimDurIfNoTouchReqdSec>".$elem[5]."</m_fPhase1StimDurIfNoTouchReqdSec>
<m_iChangeDistractorCriterion>1</m_iChangeDistractorCriterion>
<m_iColourForce>1</m_iColourForce>
<m_iColourVariation>1</m_iColourVariation>
<m_iDistractorDWORMultiplier>1</m_iDistractorDWORMultiplier>
<m_iDistractorMethod>1</m_iDistractorMethod>
<m_iIncreaseCriterion>15</m_iIncreaseCriterion>
<m_iInitiationMethod>".$elem[1]."</m_iInitiationMethod>
<m_iLevelDWORMultiplier>1</m_iLevelDWORMultiplier>
<m_iLevelMethod>0</m_iLevelMethod>
<m_iMaxTrials>1</m_iMaxTrials>
<m_iPhase1LocationVectorMultiplier>1</m_iPhase1LocationVectorMultiplier>
<m_iPhase2LocationVectorMultiplier>1</m_iPhase2LocationVectorMultiplier>
<m_iStartWithStimulus>0</m_iStartWithStimulus>
<m_iStartingLevel>1</m_iStartingLevel>
<m_iStimulusSelectionTechnique>0</m_iStimulusSelectionTechnique>
<m_iStimulusSet>".$elem[9]."</m_iStimulusSet>
<m_iStimulusWithinSet>32</m_iStimulusWithinSet>
<m_iStimulusWithinSubset>0</m_iStimulusWithinSubset>
<m_iTrialsToAvoidRepeatsOver>5</m_iTrialsToAvoidRepeatsOver>
<m_iVariant>0</m_iVariant>
<m_viNumDistractors>1</m_viNumDistractors>
<m_viPhase1Locations>4</m_viPhase1Locations>
<m_viPhase2Locations>3,5</m_viPhase2Locations>
<m_locationset>
<Location_0_X>183</Location_0_X>
<Location_0_Y>137</Location_0_Y>
<Location_1_X>500</Location_1_X>
<Location_1_Y>137</Location_1_Y>
<Location_2_X>816</Location_2_X>
<Location_2_Y>137</Location_2_Y>
<Location_3_X>183</Location_3_X>
<Location_3_Y>375</Location_3_Y>
<Location_4_X>500</Location_4_X>
<Location_4_Y>375</Location_4_Y>
<Location_5_X>816</Location_5_X>
<Location_5_Y>375</Location_5_Y>
<Location_6_X>183</Location_6_X>
<Location_6_Y>612</Location_6_Y>
<Location_7_X>500</Location_7_X>
<Location_7_Y>612</Location_7_Y>
<Location_8_X>816</Location_8_X>
<Location_8_Y>612</Location_8_Y>
<NumLocations>9</NumLocations>
<m_bMaxSizeSpecified>0</m_bMaxSizeSpecified>
<m_bMinSizeSpecified>1</m_bMinSizeSpecified>
<m_iMaxSize>0</m_iMaxSize>
<m_iMinSize>2</m_iMinSize>
</m_locationset>
</DMTS>
</Task_0>
</ModuleConfigurations>
</MonkeyCantab>";


	fputs($file,$str);
	fclose($file);

}


?>