<option>univcam_IDED_shape</option>
<option>univcam_IDED_line</option>
<option>camcog_pal0</option>
<option>camcog_pal1</option>
<option>camcog_pal2</option>
<option>camcog_pal3</option>
<option>camcog_pal4</option>
<option>camcog_mdms0</option>
<option>camcog_mdms5</option>
<option>camcog_mdms6</option>
<option>camcog_mdms7</option>
<option>camcog_star0</option>
<option>camcog_star1</option>
<option>camcog_star2</option>
<option>camcog_star3</option>
<option>camcog_star4</option>
<option>camcog_nedi0shape</option>
<option>camcog_nedi0line</option>
<option>camcog_nedi1shape</option>
<option>camcog_nedi1line</option>
<option>camcog_nedi2shape</option>
<option>camcog_nedi2line</option>
<option>camcog_nedi3shape</option>
<option>camcog_nedi3line</option>
<option>camcog_nedi4shape</option>
<option>camcog_nedi4line</option>
<option>camcog_nedi5shape</option>
<option>camcog_nedi5line</option>
<option>camcog_nedi6shape</option>
<option>camcog_nedi6line</option>
<option>camcog_nedi7shape</option>
<option>camcog_nedi7line</option>
<option>camcog_nedi8shape</option>
<option>camcog_nedi8line</option>
<option>camcog_pal5</option>